version: '3.8'

services:
  app:
    build: .
    container_name: ipam-activation-generator-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ipam_activation_generator
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./prisma:/app/prisma

  db:
    image: postgres:15-alpine
    container_name: ipam-activation-generator-db
    environment:
      POSTGRES_DB: ipam_activation_generator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: 