version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ipam-activation-generator-db
    environment:
      POSTGRES_DB: ipam_activation_generator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"  # 避免与其他Postgres容器冲突
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: ipam-activation-generator-app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ipam_activation_generator
    depends_on:
      - db
    restart: unless-stopped

  ipam-activation-migrate:
    build: .
    container_name: ipam-activation-migrate
    command: npx prisma db push
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ipam_activation_generator
    depends_on:
      - db
    restart: "no"
    user: root

volumes:
  pgdata: